<section>
    <aside>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
        <p>foo</p>
    </aside>

    <article>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
        <p>bar</p>
    </article>
</section>
